const API_URI = "http://localhost:4000";
const ITEMCARD_CHARACTER_PICTURE_DIMENSION = "portrait_uncanny";
const CHARACTER_PICTURE_SQUARE_DIMENSION = "standard_xlarge";

export { API_URI };
export { ITEMCARD_CHARACTER_PICTURE_DIMENSION };
export { CHARACTER_PICTURE_SQUARE_DIMENSION };
